/*
 * @author Esteban Valderrama
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Procedures.SendEmail;
import Classes.Utilities;
//import Forms.ModelsUI;
import Procedures.LoadFiles;
import Procedures.ShowMessages;
import java.awt.Color;
//import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 */
public class EmailUI extends javax.swing.JFrame {
    
    public File attachment;

    /**
     * Creates new form EmailUI
     */
    public EmailUI() {
        initComponents();
        btnBrowse.setVisible(false);
        this.setLocationRelativeTo(null); // Open ModelsUI GUI in the center of the screen 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        lblAttachment = new javax.swing.JLabel();
        txtAttachment = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        cmbRole = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblFirstname.setText("*First Name:");

        txtFirstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFirstnameMouseClicked(evt);
            }
        });
        txtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyReleased(evt);
            }
        });

        lblLastname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblLastname.setText("*Last Name:");

        txtLastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastnameMouseClicked(evt);
            }
        });
        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastnameKeyReleased(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setText("*Email:");

        txtEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmailAddress.setMinimumSize(new java.awt.Dimension(6, 20));
        txtEmailAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailAddressMouseClicked(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblSubject.setText("*Country:");

        txtSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSubjectMouseClicked(evt);
            }
        });
        txtSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubjectKeyReleased(evt);
            }
        });

        lblAttachment.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblAttachment.setText("Attachment:");

        txtAttachment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblMessage.setText("*Institution:");

        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMessage.setLineWrap(true);
        txtMessage.setRows(5);
        txtMessage.setWrapStyleWord(true);
        txtMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMessageMouseClicked(evt);
            }
        });
        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessageKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtMessage);

        cmbRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*Select your activity:", "Education", "Research" }));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("*Required Field");

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBrowse.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFirstname)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lblLastname))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(lblEmail)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblSubject)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblAttachment)
                                .addGap(18, 18, 18)
                                .addComponent(txtAttachment, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBrowse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblMessage)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblFirstname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastname))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubject))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttachment)
                    .addComponent(txtAttachment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstnameMouseClicked
        lblFirstname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFirstnameMouseClicked

    private void txtFirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyReleased
        // Validate firstname field only for letters
        lblFirstname.setForeground(Color.BLACK);
        if (txtFirstname.getText().matches("[0.0-9--]*")
            || txtFirstname.getText().matches("[\\\\\\\\`!\\\"\\#$%&()*+,"
                + "./:;<=>?@\\\\[\\\\]^_{|}~]+")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getStrTextbox(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            txtFirstname.requestFocus();
            txtFirstname.selectAll();
        }
    }//GEN-LAST:event_txtFirstnameKeyReleased

    private void txtLastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastnameMouseClicked
        lblLastname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtLastnameMouseClicked

    private void txtLastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyReleased
        // Validate lastname field only for letters
        lblLastname.setForeground(Color.BLACK);
        if (txtLastname.getText().matches("[0.0-9--]*") ||
            txtLastname.getText().matches("[\\\\\\\\`!\\\"\\#$%&()*+,"
                + "./:;<=>?@\\\\[\\\\]^_{|}~]+")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getStrTextbox(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLastname.requestFocus();
            txtLastname.selectAll();
        }
    }//GEN-LAST:event_txtLastnameKeyReleased

    private void txtEmailAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailAddressMouseClicked
        lblEmail.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEmailAddressMouseClicked

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // NOT VALID
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSubjectMouseClicked
        lblSubject.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSubjectMouseClicked

    private void txtSubjectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubjectKeyReleased
        // Validate subject field only for letters
        lblSubject.setForeground(Color.BLACK);
        if (txtSubject.getText().matches("[\\\\\\\\`!\\\"\\#$%&()*+,"
            + "./:;<=>?@\\\\[\\\\]^_{|}~]+")){
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(null, ShowMessages.getStrTextbox(),
            "ERROR", JOptionPane.ERROR_MESSAGE);
        txtSubject.requestFocus();
        txtSubject.selectAll();
        }
    }//GEN-LAST:event_txtSubjectKeyReleased

    private void txtMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMessageMouseClicked
        lblMessage.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtMessageMouseClicked

    private void txtMessageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyReleased
        lblMessage.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtMessageKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        Object SelectedItem = cmbRole.getSelectedItem();
        // Check if name is empty
        if ("".equals(txtFirstname.getText())){
            txtFirstname.setText("");
            txtFirstname.requestFocus();
            lblFirstname.setForeground(Color.RED);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            // Check if lastname is empty
        }else if ("".equals(txtLastname.getText())){
            txtLastname.setText("");
            txtLastname.requestFocus();
            lblLastname.setForeground(Color.RED);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            // Check if email is empty
        }else if ("".equals(txtEmailAddress.getText())){
            txtEmailAddress.setText("");
            txtEmailAddress.requestFocus();
            lblEmail.setForeground(Color.RED);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            // Check if subject is empty
        }else if ("".equals(txtSubject.getText())){
            txtSubject.setText("");
            txtSubject.requestFocus();
            lblSubject.setForeground(Color.RED);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            // Check if message is empty
        }else if ("".equals(txtMessage.getText())){
            txtMessage.setText("");
            txtMessage.requestFocus();
            lblMessage.setForeground(Color.RED);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
            // Check if activity is empty
        }else if ("*Select your activity:".equals(String.valueOf(SelectedItem))){
            cmbRole.requestFocus();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, ShowMessages.getMissingInfo(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            // Save inputs in variables
            String name = txtFirstname.getText();
            String lastname = txtLastname.getText();
            String email = txtEmailAddress.getText();
            String role = String.valueOf(SelectedItem);
            // Save date & time
            Calendar c = new GregorianCalendar();
            c.set(Calendar.HOUR_OF_DAY, 0); // Hours 0 - 23
            c.set(Calendar.MINUTE, 0); // Minutes 0 - 59
            c.set(Calendar.SECOND, 0); // Seconds 0 - 59
            Date d1 = c.getTime(); // The midnight, that's the first second of the day.
            String date = d1.toString();
            // Compose message
            String message = "From: " + name + " " + lastname + "\n"
            + email + " - " + role + "\n"
            + date + "\n"
            + "==================================================="
            + "==========================\n\n\n"
            + txtMessage.getText();
            // Compose subject
            String subject = txtSubject.getText() + " - " + email;
            // Save attachment
// automatically upload the simulationresults.zip file
//
            String attachmentPath = txtAttachment.getText();
            attachment = LoadFiles.load_attachment(); // Attach file
            txtAttachment.setText(Utilities.getAttachment());
            // email & password
//            String from = "csdfts.comphys@gmail.com";
             String from = "false@gmail.com";
             String password = "falsepass";
            // Recipients
//            String[] to = {"csdfts.comphys@gmail.com"};
             String[] to = {email};
            if (attachment == null){
                SendEmail.send_mail_noAttachment(from, password, to, subject,
                    message);
            }else{
                SendEmail.send_mail_Attachment(from, password, to, subject,
                    message, attachment,
                    attachmentPath);
            }
//            if(Utilities.getEmailSent()){
//                JOptionPane.showMessageDialog(null, ShowMessages.getEmailSent(),
//                    "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
//                dispose();
//            } else{
//                Toolkit.getDefaultToolkit().beep();
//                JOptionPane.showMessageDialog(null, ShowMessages.getEmailNotSent(),
//                    "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
//                dispose();
 //           }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        attachment = LoadFiles.load_attachment(); // Attach file
        txtAttachment.setText(Utilities.getAttachment());
    }//GEN-LAST:event_btnBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSubmit;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttachment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextField txtAttachment;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
